require 'hoe'
require './lib/bytes/version.rb'


Hoe.spec 'bytes' do

  self.version = Cocos::Module::Bytes::VERSION

  self.summary = "bytes - bits 'n' bytes made easy/easier incl. new buffer helper / wrapper class to help with the string byte vs character dichotomy"
  self.description = summary


  self.urls    = { home: 'https://github.com/rubycocos/core' }

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
