require 'hoe'
require './lib/date-formats/version.rb'

Hoe.spec 'date-formats' do

  self.version = DateFormats::VERSION

  self.summary = "date-formats - read / parse and print dates (and times) from around the world"
  self.description = summary

  self.urls = { home: 'https://github.com/rubycoco/core' }

  self.author = 'Gerald Bauer'
  self.email  = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = []

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }
end
