require 'hoe'
require './lib/props/version.rb'

Hoe.spec 'props' do

  self.version = ConfUtils::VERSION

  self.summary = 'props - Manage Settings Hierachies (Commandline, User, Home, Defaults, etc.)'
  self.description = summary

  self.urls    = ['https://github.com/rubylibs/props']

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'HISTORY.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
      ['iniparser', '>=0.1.0'],
    ]

  self.spec_extras = {
    required_ruby_version: '>= 1.9.2'
  }

end
