require 'hoe'
require './lib/iniparser/version.rb'

Hoe.spec 'iniparser' do

  self.version = IniParser::VERSION

  self.summary = 'iniparser - read / parse INI configuration, settings and data files into a hash (incl. named subsections)'
  self.description = summary

  self.urls    = { home: 'https://github.com/rubycoco/core' }

  self.author  = 'Gerald Bauer'
  self.email   = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
