require 'hoe'
require './lib/alphabets/version.rb'

Hoe.spec 'alphabets' do

  self.version = Alphabet::VERSION

  self.summary = "alphabets - alphabet (a-z) helpers incl. unaccent, downcase, variants, and more"
  self.description = summary

  self.urls = { home: 'https://github.com/rubycoco/core' }

  self.author = 'Gerald Bauer'
  self.email  = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = []

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
